### ISSUE TITLE
Review existing code and check documentation

### ISSUE THREAD

**Issue by kaufmanno** [kaufmanno/GSDMA#10]
Look at the available code (in python files '.py' and jupyter notebooks '.ipynb') to understand what it is used for and check if this is properly explained in the documentation.  Make suggestions of improvements.

**Comment by kaufmanno** [comment]
Let's split this issue into two issues: #12 and

**Comment by kaufmanno** [comment]
In the documentation, the explanation of the "Example of reading borehole data from electrodes string files inserted into a sqlite database" is not fully correct. -> we opened issue  to improve it.

**Comment by YanickNdepo** [comment]
The overall directories structure of the project does not facilitate searching file. we must make a clear structure with specific directories like notebooks, test_notebooks, database (data files and sqliteDB file), ...

**Comment by YanickNdepo** [comment]
For the structure of the documentation, titles (H1, H2, …) are note used efficiently. 
For enhancement, try if possible to make a documentation with sections and subsections by using these styles (H1, H2, ...).
Another thing is to make a sort of menubar (at the leftside) that allows to scroll the main text without scroll the menu. This will allows the reader to navigate easily in the documentation (example of https://striplog.readthedocs.io/en/latest/api/striplog.utils.html).

**Comment by YanickNdepo** [comment]
Another thing (always in the documentation) is to make a sort of menubar (at the leftside) that allows to scroll the main text without scroll the menu. This will allows the reader to navigate easily in the documentation (example of https://striplog.readthedocs.io/en/latest/api/striplog.utils.html).

**Comment by YanickNdepo** [comment]
For striplog, improve the code to show only legends that are used beside the striplog. If it is possible, show the value of depth (1m, 2m, ...) to avoid reading difficulties

**Comment by YanickNdepo** [comment]
There is no informations about the interest of each steps in each section of the documentation. The purpose of each task must be wrote for a better understanding of code.

**Comment by kaufmanno** [comment]
> The overall directories structure of the project does not facilitate searching file. we must make a clear structure with specific directories like notebooks, test_notebooks, database (data files and sqliteDB file), ... Also, put a single notebook, in which all the 'small' codes are gathered, in the root directory will be more efficient for executing code step by step.

Could you open an issue?
