### ISSUE TITLE
Project update_legend_cmap() fails

### ISSUE THREAD

**Issue by kaufmanno** [kaufmanno/GSDMA#118]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-38-f6ea5a9c4a62> in <module>
----> 1 p.update_legend_cmap()

~/PycharmProjects/GSDMA/core/core.py in update_legend_cmap(self, repr_attribute_list, legend_dict, width, update_all_attrib, update_bh3d_legend, update_project_legend, verbose)
    159             legend_dict = self.legend_dict
    160 
--> 161         synth_leg, detail_leg = build_bh3d_legend_cmap(
    162             bh3d_list=self.boreholes_3d, legend_dict=legend_dict,
    163             repr_attrib_list=repr_attribute_list, width=width, compute_all=update_all_attrib,

~/PycharmProjects/GSDMA/utils/omf.py in build_bh3d_legend_cmap(bh3d_list, legend_dict, repr_attrib_list, width, compute_all, update_bh3d_legend, update_given_legend, verbose)
     93         if verbose and verb in verbose:
     94             print(f'BLCMap for : {attr}\n---------------------------------------')
---> 95         if not isinstance(legend_dict[attr]['legend'], Legend):
     96             raise (TypeError('legend must be a Striplog.Legend object. Check the docstring!'))
     97 

~/.local/share/virtualenvs/GSDMA-tJb-HgI6/lib/python3.8/site-packages/striplog/legend.py in __getitem__(self, key)
    368             return Legend(result)
    369         else:
--> 370             return self.__list[key]
    371 
    372     def __setitem__(self, key, value):

TypeError: list indices must be integers or slices, not str

**Comment by YanickNdepo** [comment]
fixed
