### ISSUE TITLE
Sketch the table of contents of the documentation

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#18]

**Comment by CampeolQ** [comment]
The end of the table of content is not fully respected in the presentation.

**Comment by kaufmanno** [comment]
@Joseph-Wandji Can you do this and improve the index.rst?

**Comment by Joseph-Wandji** [comment]
First integrated table content has been done for utils modules with better understading to how do us make for the rest of modules available over project.
