### ISSUE TITLE
Add information in the striplog representation of boreholes

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#19]
Additional features wanted:
- Add a title and the scale on the striplog representation;
- Represent in the legend only the observed lithologies.

**Comment by CampeolQ** [comment]
Add a title and the scale on the striplog representation

**Comment by CampeolQ** [comment]
Represents in the legend only the observed lithologies.

**Comment by YanickNdepo** [comment]
fixed !
