### ISSUE TITLE
Split documentation into API documentation and tutorials/examples - sphinx-gallery

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#20]

**Comment by kaufmanno** [comment]
One may split documentation into API documentation and tutorials/examples. [sphinx-gallery](https://sphinx-gallery.github.io/stable/index.html) might be a way to expose examples.

**Comment by CampeolQ** [comment]
In the section "Creation of Geopackage from SQL", explain the reason of the section create gpkg from shp, Copy Tables, etc.

**Comment by Joseph-Wandji** [comment]
With aim to propose from a little description of some information about GSDM 2020, what users have to understand before.

**Comment by Joseph-Wandji** [comment]
@CampeolQ @JorisCoronGSDM @JorisCoronGSDM  Pleasure, to generate and copy  notebook (.nb)) under module (.py) into utils folder

**Comment by kaufmanno** [comment]
Splitted this issue into two separate issues : #77 and #78
