### ISSUE TITLE
Sphinx & Restructured text for codes from Numpydoc V1.2.

### ISSUE THREAD

**Issue by Joseph-Wandji** [kaufmanno/GSDMA#22]
This one has been closed because another issue is created in [Review the table of contents of the documentation](https://github.com/kaufmanno/GSDMA/issues/10)

**Comment by kaufmanno** [comment]
@Joseph-Wandji Could you review your comment? It seems a verb is missing and this issue refers to itself...

**Comment by kaufmanno** [comment]
Duplicate of issue #35? @Joseph-Wandji can we close this one?
