### ISSUE TITLE
Enhance documentation display

### ISSUE THREAD

**Issue by YanickNdepo** [kaufmanno/GSDMA#23]
make the documentation with readthedocs theme ([example](https://opengeovis.github.io/omfvista/content/omfvista/volume.html))

**Comment by Joseph-Wandji** [comment]
We have to use specially Sphinx and rST for make this task into numpydoc?

**Comment by kaufmanno** [comment]
@Joseph-Wandji Numpydoc is an Sphinx extension. You should have a look at [this link](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) to understand how to write docstrings into functions and methods.

**Comment by Joseph-Wandji** [comment]
Well received!
    Le dimanche 22 novembre 2020 à 15:31:05 UTC+1, kaufmanno <notifications@github.com> a écrit :  
 
 


@Joseph-Wandji Numpydoc is an Sphinx extension. You should have a look at this link to understand how to write docstrings into functions and methods.

**Comment by kaufmanno** [comment]
@YanickNdepo could you edit the first post to better specify this issue?

**Comment by kaufmanno** [comment]
If you want a readthedocs style then you need to install (with pipenv) the sphinx-rtd-theme package and configure your sphinx to use this theme.
