### ISSUE TITLE
Test display_list_of-_intervals.ipynb

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#29]
Follow this [link](https://github.com/kaufmanno/GSDMA/blob/master/playground/display_list_of-_intervals.ipynb)

**Comment by Joseph-Wandji** [comment]
Hey everyone
I finished to read this code and I emphasis to run. But this error display on my screen.
Please, I need help @JorisCoronGSDM 

from striplog import Striplog, Legend, Lexicon, Interval, Component

legend = Legend.builtin('NSDOE')

lexicon = Lexicon.default()

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-6907e2173ebf> in <module>
----> 1 from striplog import Striplog, Legend, Lexicon, Interval, Component
      2 legend = Legend.builtin('NSDOE')
      3 lexicon = Lexicon.default()

ModuleNotFoundError: No module named 'striplog

**Comment by JorisCoronGSDM** [comment]
Hello Joseph,

I’ve just tried to run the code and i didn’t encounter any error.
Let’s talk about this during our meetin tomorrow if the error persist for you !
Have a good evening.

Joris


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Joseph-Wandji<mailto:notifications@github.com>
Envoyé le :samedi 14 novembre 2020 19:42
À : kaufmanno/GSDMA<mailto:GSDMA@noreply.github.com>
Cc : JorisCoronGSDM<mailto:saccoma@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [kaufmanno/GSDMA] Test display_list_of-_intervals.ipynb (#29)


Hey everyone
I finished to read this code and I emphasis to run. But this error display on my screen.
Please, I need help @JorisCoronGSDM<https://github.com/JorisCoronGSDM>

from striplog import Striplog, Legend, Lexicon, Interval, Component

legend = Legend.builtin('NSDOE')

lexicon = Lexicon.default()


ModuleNotFoundError Traceback (most recent call last)
in
----> 1 from striplog import Striplog, Legend, Lexicon, Interval, Component
2 legend = Legend.builtin('NSDOE')
3 lexicon = Lexicon.default()

ModuleNotFoundError: No module named 'striplog

**Comment by Joseph-Wandji** [comment]
This code run perfectly. We have created a .env to correct it on my GDMA project.
