### ISSUE TITLE
first run of an implementation of  API documentation with sphinx-autodoc  

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#35]

**Comment by kaufmanno** [comment]
Linked to issue #8

**Comment by Joseph-Wandji** [comment]
I have reviewed codes into utils folder from numpydocs configuration. 
pip install numpydoc permit for using Sphinx extension to support docstrings in Numpy format
Currently, I am working to generate documentation.

**Comment by Joseph-Wandji** [comment]
I first generate html page within conf file in Numpydoc.
I currently improve conf file and show  tables content related to the both modules  db_tools and read_flat_files. 
Useful [link](https://shunsvineyard.info/2019/09/19/use-sphinx-for-python-documentation/#3-workflow) to acheive them.

**Comment by Joseph-Wandji** [comment]
First documentation is already available but the readme is not integrated. I try to make and possible review the previous table contents into GSDMA project 2019. With aim to create a simple way to show step by step some parts our work.
