### ISSUE TITLE
Implement relative path in each notebook

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#36]
Relative paths are important because it allows any user to compile the notebook without specifying his personal path.
Some notebook already implement relative path, as example, [this one](https://github.com/kaufmanno/GSDMA/blob/improvedocs/playground/SQL_test_good-last.ipynb). 
Use the same idea.

**Comment by Joseph-Wandji** [comment]
Using this command [line](work_dir = '../data/boreholes/'), it is very important to ensure the path of GDMSA project is already good for run whole notebook.
I delete some notebook files (Untitled)  are empty into playground folder.
