### ISSUE TITLE
Replace fct defined in the code by fct defined in utils

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#37]
It will be a part of the documentation because it allows to understand the functions define in [utils](https://github.com/kaufmanno/GSDMA/tree/improvedocs/utils).

**Comment by JorisCoronGSDM** [comment]
The fct "db_copy_sqlite3_tables" in [link](https://github.com/kaufmanno/GSDMA/blob/improvedocs/playground/gdf_sql3_.ipynb) and the fct "add_interval_list" in [link](https://github.com/kaufmanno/GSDMA/blob/improvedocs/playground/display_list_of-_intervals.ipynb) have been defined in [utils](https://github.com/kaufmanno/GSDMA/tree/improvedocs/utils) and used from there.
