### ISSUE TITLE
Learn more about Striplog, pyvista and OMF

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#42]

**Comment by kaufmanno** [comment]
linked with #24

**Comment by YanickNdepo** [comment]
1. we have learned with documentations how to create omf project and objects
2. we know that a borehole can be represented by a omf lineset object 
3. intervals can be represented by segments (belonging to a lineset object) where vertices will be the 'top' and the 'base' of an interval

**Comment by YanickNdepo** [comment]
To do : 
1. fill the classes attributes and methods to know what must be implemented or is ever implemented (inheritance if needed)
2. write codes to implement the objects
3.

**Comment by kaufmanno** [comment]
It is a general issue -> I will close it
