### ISSUE TITLE
Propose an UML class diagram for the project

### ISSUE THREAD

**Issue by kaufmanno** [kaufmanno/GSDMA#45]

**Comment by YanickNdepo** [comment]
the proposed UML class is below : 
![sketch_of _classes_v2_mod](https://user-images.githubusercontent.com/73942625/101145518-2f90cb00-361a-11eb-9b79-5aefb43e0a00.png)

**Comment by YanickNdepo** [comment]
the proposed UML class diagram is below : 
![sketch_of _classes_v2_mod](https://user-images.githubusercontent.com/73942625/101147485-b8106b00-361c-11eb-9f7d-5c060de15d0e.png)
