### ISSUE TITLE
Learn more about ORM

### ISSUE THREAD

**Issue by kaufmanno** [kaufmanno/GSDMA#46]
Identify key operations to learn in ORM and learn how to implement them with sqlalchemy

**Comment by kaufmanno** [comment]
@CampeolQ you should have a look at [this notebook](https://github.com/kaufmanno/GSDMA/blob/orm/playground/sqlachemy_one_to_many_dict.ipynb) I added in the orm branch...

**Comment by CampeolQ** [comment]
The purpose of using a context manager is to create a secure session when adding data to the database. Indeed, when an invalid data is added, the session emits an error and does not add the data.

See the [notebook](https://github.com/kaufmanno/GSDMA/blob/orm/playground/sqlalchemy_Borehole_Interval_Component.ipynb) where the ORM is implemented. 

In this notebook, four classes are created related to the striplog object and borehole objects are implemented manually into de test_db3.db database.
