### ISSUE TITLE
intervals as pyvista.cylinder object

### ISSUE THREAD

**Issue by YanickNdepo** [kaufmanno/GSDMA#47]
- try to represent each interval in striplog by pyvista.cylinder object

- texture the cylinder with a rock (component) image

- pile up all the cylinders to form a 3D borehole

**Comment by kaufmanno** [comment]
@JorisCoronGSDM Can you document this and close the issue?

**Comment by JorisCoronGSDM** [comment]
This [notebook](https://github.com/kaufmanno/GSDMA/blob/omf/playground/simple_borehole_rendering_with_textures.ipynb) expose an exemple to create a borehole from several cylinders with différents textures using pyvista. @YanickNdepo
