### ISSUE TITLE
Implement the ORM approach to create the database

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#50]

**Comment by CampeolQ** [comment]
Related to the notebook : 
[sqlalchemy_Borehole_Interval_with_Striplog.ipynb ](https://github.com/kaufmanno/GSDMA/blob/orm/playground/sqlalchemy_Borehole_Interval_with_Striplog.ipynb)

Four classes are implemented to create a borehole object at this time. There are the class of Borehole, the one of component, the one of Interval and the one which link the interval table to component table (because some components may occur into one Interval and some interval may possess the same component, relationship many to many)

**Comment by CampeolQ** [comment]
The class Interval has to be improve by introducing the attributes "top" and "base" which are objects belonging to a new class "Position". 
In this new class, the user will introduce the upper, "middle" and "top" values relative to the "top" or "base" object.

**Comment by CampeolQ** [comment]
In the loop where data are read and placed into a drill object, components must also be added automatically.
To do this, the component dictionary must be used to find out which components are located in each interval and then add them manually using the indexes of the dictionnary.

**Comment by CampeolQ** [comment]
At the end, create methods with all the necessary functions (read function, add function, etc.) created in the notebook in the class borehole to implement a real object-oriented approach.

**Comment by kaufmanno** [comment]
@CampeolQ Can you split this into 3 issues?

**Comment by CampeolQ** [comment]
This issue is splited into three issue #53 #52 and #51.
