### ISSUE TITLE
ORM Implement the read function

### ISSUE THREAD

**Issue by CampeolQ** [kaufmanno/GSDMA#62]

**Comment by kaufmanno** [comment]
@CampeolQ  What should the read function do? Would it be a method in a class?

**Comment by CampeolQ** [comment]
The function of reading a .las file used to create a dictionary that will be added into the database as a borehole (presented in issue 38), is created : 

'''
int_id = 0
bh_id = 0
pos_id = 0
boreholes = []
components = []
comp_id = 0
component_dict={}
pos_dict = {}
for bh, filename in borehole_dict.items():
    interval_number = 0
    boreholes.append(Borehole(id=bh))
    with open(filename, 'r') as las3:
        strip = Striplog.from_las3(las3.read(), lexicon)
    for c in strip.components:
        if c not in component_dict.keys():
            component_dict.update({c:comp_id})
            comp_id += 1
    d ={}
    for interval in strip:
        top = Position(id=pos_id, upper=interval.top.upper, middle=interval.top.middle,  lower=interval.top.lower)
        base = Position(id=pos_id+1, upper=interval.base.upper, middle=interval.base.middle,  lower=interval.base.lower)
        d.update({int_id:{'description':interval.description, 'interval_number' : interval_number, 
                          'top': top, 'base': base
                         }})
        interval_number+=1
        int_id += 1
        pos_id += 2

    print(d)
    boreholes[bh_id].intervals_values = d
    #boreholes[bh_id].components_values = c
    bh_id += 1 
components = {v:k for k,v in component_dict.items()}
'''
