### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by kaufmanno** [kaufmanno/GSDMA#7]
A good README should include several sections as stated in [this document](https://guides.lib.berkeley.edu/how-to-write-good-documentation)

**Comment by CampeolQ** [comment]
A first improvement of README.md has been achieved.

**Comment by CampeolQ** [comment]
The "Contributing" and "Citation" parts are still to be completed.

**Comment by CampeolQ** [comment]
@JorisCoronGSDM, You should have a look on other README.md to finish this issue and complete the "Contributing" and "Citation" parts.

**Comment by JorisCoronGSDM** [comment]
-The contributing part is completed: [new file](https://github.com/kaufmanno/GSDMA/blob/improvedocs/CONTRIBUTING.md) created and linked in the [readme](https://github.com/kaufmanno/GSDMA/blob/improvedocs/README.md) (the link will have to  be mofified when the Contributing file will be merged to Master)
-I did some  minor corrections in the [readme](https://github.com/kaufmanno/GSDMA/blob/improvedocs/README.md).

**Comment by JorisCoronGSDM** [comment]
Citing the depository involve to make it public. Then we could generate a DOI using [Zenodo](https://zenodo.org/).

**Comment by JorisCoronGSDM** [comment]
D'ont matter the remark about the link change when merging to master in [link](https://github.com/kaufmanno/GSDMA/issues/7#issuecomment-743123176), the link is now written as ./CONTRIBUTING.md and should work on any branch.
