### ISSUE TITLE
Generate the updated API documentation using sphinx-apidoc

### ISSUE THREAD

**Issue by kaufmanno** [kaufmanno/GSDMA#77]
**1- Set-up the sphinx conf.py correctly**

Insert into the conf.py the api.ext.autodoc extension into conf.py and set the correct path to the parent directory of the project packages (see [this link](https://medium.com/better-programming/auto-documenting-a-python-project-using-sphinx-8878f9ddc6e9)). 

**2- Test it with the existing docstrings**

Make the html docs, look for errors during the make process and solve them

**3- Apply it to the updated docstrings**

Once issues #71, #72, #73, #74 and #75 are closed,  test it with the updated docstrings. Fix or report remaining problems to docstrings authors.

**4- Generate the final API docs and close this issue**
Once everything is fixed, generate the final API doc and close this issue.

**Comment by Joseph-Wandji** [comment]
With help to Professor, we build a simple API documentation for the whole modules into utils, core and examples.
