### ISSUE TITLE
Soil samples 3D display

### ISSUE THREAD

**Issue by YanickNdepo** [kaufmanno/GSDMA#99]
implement soil sample representation with different colors according to lithology, pollutant and intensity of pollutant concentration

**Comment by kaufmanno** [comment]
I am working on this one !

**Comment by YanickNdepo** [comment]
In the OMF part of the project, samples are represented as Striplog.Component object. So an interval can contain one or more components (or samples) and each sample is refered to an attribute like 'lithology' or a pollutant ('Benzene', etc.) and so on.

**Comment by YanickNdepo** [comment]
To get correct samples indices in an interval, the function 'find_component_from_attrib()' has been implemented. it returns the index of the first component that matches with the attribute key (e.g : 'lithology') in the components list of an interval.
